// Export utility functions for different formats

export const exportUtils = {
  // Export as Markdown file
  exportAsMarkdown(
    code: string,
    language: string,
    review?: string,
    correction?: string
  ): void {
    const timestamp = new Date().toISOString();
    let content = `# Code Review Report\n\n`;
    content += `**Date:** ${new Date().toLocaleString('cs-CZ')}\n`;
    content += `**Language:** ${language}\n\n`;

    content += `## Original Code\n\n\`\`\`${language.toLowerCase()}\n${code}\n\`\`\`\n\n`;

    if (review) {
      content += `## Code Review\n\n${review}\n\n`;
    }

    if (correction) {
      content += `## Corrected Code\n\n\`\`\`${language.toLowerCase()}\n${correction}\n\`\`\`\n\n`;
    }

    content += `---\n*Generated by Gemini Code Reviewer*\n`;

    this.downloadFile(content, `code-review-${timestamp}.md`, 'text/markdown');
  },

  // Export as JSON
  exportAsJSON(data: {
    code: string;
    language: string;
    review?: string;
    correction?: string;
    model?: string;
    timestamp?: number;
  }): void {
    const exportData = {
      ...data,
      timestamp: data.timestamp || Date.now(),
      exportDate: new Date().toISOString(),
    };

    const jsonString = JSON.stringify(exportData, null, 2);
    const timestamp = new Date().toISOString();

    this.downloadFile(jsonString, `code-review-${timestamp}.json`, 'application/json');
  },

  // Export as HTML (for PDF conversion)
  exportAsHTML(
    code: string,
    language: string,
    review?: string,
    correction?: string
  ): void {
    const timestamp = new Date().toISOString();

    const html = `
<!DOCTYPE html>
<html lang="cs">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Code Review Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      max-width: 900px;
      margin: 40px auto;
      padding: 20px;
      line-height: 1.6;
      color: #333;
    }
    h1 { color: #1a1a1a; border-bottom: 3px solid #4f46e5; padding-bottom: 10px; }
    h2 { color: #4f46e5; margin-top: 30px; }
    .meta { color: #666; margin-bottom: 20px; }
    pre {
      background: #f5f5f5;
      border: 1px solid #ddd;
      border-radius: 4px;
      padding: 15px;
      overflow-x: auto;
    }
    code {
      font-family: 'Fira Code', Consolas, Monaco, 'Courier New', monospace;
      font-size: 14px;
    }
    .review {
      background: #f0f9ff;
      border-left: 4px solid #0ea5e9;
      padding: 15px;
      margin: 20px 0;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      color: #666;
      font-size: 14px;
      text-align: center;
    }
    @media print {
      body { margin: 0; }
    }
  </style>
</head>
<body>
  <h1>📋 Code Review Report</h1>

  <div class="meta">
    <strong>Date:</strong> ${new Date().toLocaleString('cs-CZ')}<br>
    <strong>Language:</strong> ${language}
  </div>

  <h2>💻 Original Code</h2>
  <pre><code>${this.escapeHTML(code)}</code></pre>

  ${review ? `
  <h2>🔍 Code Review</h2>
  <div class="review">
    ${this.markdownToHTML(review)}
  </div>
  ` : ''}

  ${correction ? `
  <h2>✨ Corrected Code</h2>
  <pre><code>${this.escapeHTML(correction)}</code></pre>
  ` : ''}

  <div class="footer">
    Generated by <strong>Gemini Code Reviewer</strong> • ${new Date().toLocaleString('cs-CZ')}
  </div>
</body>
</html>
    `.trim();

    this.downloadFile(html, `code-review-${timestamp}.html`, 'text/html');
  },

  // Helper: Download file
  downloadFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  },

  // Helper: Escape HTML
  escapeHTML(str: string): string {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
  },

  // Helper: Simple markdown to HTML converter
  markdownToHTML(markdown: string): string {
    let html = this.escapeHTML(markdown);

    // Headers
    html = html.replace(/^### (.*$)/gim, '<h3>$1</h3>');
    html = html.replace(/^## (.*$)/gim, '<h2>$1</h2>');
    html = html.replace(/^# (.*$)/gim, '<h1>$1</h1>');

    // Bold
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');

    // Italic
    html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

    // Code blocks (basic)
    html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

    // Line breaks
    html = html.replace(/\n/g, '<br>');

    return html;
  },
};
